defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: post
      title: Guessing Game by bgbrandongomez
      project: Guessing Game
      projectid: GuessingGame
      developer: bgbrandongomez
      branch: master
      description: A fun little game in which you get to guess what number the computer is thinking.
      siteurl: https://senorcontento.github.io/
